### PR TITLE
LPS-90756 Apply cards to Blogs images

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @patriciajeanperez,

This PR updates Blogs Images so that it uses the current lexicon
cards.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
Hey @adolfopa , Patty is out today so I will review this pull. Thanks!

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/68296

**Comment by austinchiang** [comment]
ci:close

**Comment by adolfopa** [comment]
Thanks Austin!

**Pull request closed without merging**
