### PR TITLE
LPS-89954 Reorganize D&M menus

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @patriciajeanperez,

Here I've reordered some of the menu options and added a
separator. Hope this doesn't break anything.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/70214

**Pull request closed without merging**
