### PR TITLE
LRQA-69764 | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LRQA-69764

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Hi @epark18! great job with updating the macros to be reusable both in Control Panel and widget. I just have a few comments, mainly on the role added to the test. Otherwise, looks good! Thanks!

**Comment by epark18** [comment]
@patriciajeanperez Thank you for the feedback! In regards to the role added, the [story ticket](https://issues.liferay.com/browse/LPS-136667) notes that the user needs additional permissions to delete and deactivate accounts which is not covered in the setup. While manual testing, I was only able to get the options to delete and deactivate when giving the Administrator role to the new user.

**Comment by patriciajeanperez** [comment]
gotcha @epark18. sorry I missed it, but the permissions can be added in `Roles Admin - Account Roles - Account Admin - Define Permissions - Accounts - Resource Permissions - Account Entry - Delete` 

I made some changes with the JSON macros to allow adding permissions to Account Roles but it's still in Brian's queue. So I will be the one to make those changes for this test to avoid conflicts.

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
