### PR TITLE
LPS-93180 Chage default sort order

### PR DESCRIPTION
**Pull request by adolfopa**
@patriciajeanperez We've changed the default sort order in D&M. Not sure if this
will affect any tests.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:documents

**Comment by patriciajeanperez** [comment]
DM failures are unrelated.

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/73138

**Pull request closed without merging**
