### PR TITLE
LPS-84324 Simplify D&M move interaction

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @patriciajeanperez,

Here we've simplified the interaction when moving files or
folders. Instead of a two step process, the user is asked for the
destination, and the item is moved immediatelly.

Previously, there was an intermediate view which would show the
selected items before selecting the destination folder.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Just started reviewing :)

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/69739

**Pull request closed without merging**
