### PR TITLE
LPS-90484 Use Lexicon paginator

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @patriciajeanperez,

This changes the styles/markup of the pagination bar in blogs.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:blogs

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/73329

**Pull request closed without merging**
