### PR TITLE
LRQA-73679 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-73679

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:sf

**Review by patriciajeanperez — COMMENTED** [review]
Thank you, @melodywu! Left some comments including ones we already discussed on Slack. 
- No need to add paths that we are not going to use
- Navigate via URL. We should already have smoke tests that navigate to portlets via UI.
- Update BDD statements and make sure the setup is in the Given block, the actions are in the When block. All your assertions are in the Then block, so those are good.
- Can we update the adding account role macro be usable for Owned and Shared type?
- Please make sure to update the title and description to include all LRQAs included in this PR

cc @sharryxue

**Pull request closed without merging**
