### PR TITLE
LPS-94858 Disable actions for non visible entries

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @patriciajeanperez,

In this PR I disable the dropdown action for entries that are not visible in the
Shared Content app.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:sharing

**Comment by patriciajeanperez** [comment]
ci:test:sharing

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/72452

**Pull request closed without merging**
