### PR TITLE
LRQA-71834 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-71834

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
ci:test

**Comment by patriciajeanperez** [comment]
ci:stop

**Comment by patriciajeanperez** [comment]
@melodywu Some tests have the `property portal.acceptance = "melody";` set. Please also run SF before committing your changes so you wouldn't need a separate commit just for SF fixes. Please fix and resend, thanks!

**Pull request closed without merging**
