### PR TITLE
LRQA-34737 | master

### PR DESCRIPTION
**Pull request by patriciajeanperez**

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
@patriciajeanperez - Here's a set of links to this particular pull request test:
https://github.com/patriciajeanperez/liferay-portal/pull/39#issuecomment-334876214

<ul>
<li><a href="https://files.liferay.com/private/bundles/test-1-16/jobs/test-portal-acceptance-pullrequest%28master%29/builds/1743/liferay-portal-bundle-tomcat.zip">files.liferay.com</a></li>
<li><a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-16/jobs/test-portal-acceptance-pullrequest%28master%29/builds/1743/liferay-portal-bundle-tomcat.zip">mirrors.dlc.liferay.com</a></li>
<li><a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-16/jobs/test-portal-acceptance-pullrequest%28master%29/builds/1743/liferay-portal-bundle-tomcat.zip">mirrors.lax.liferay.com</a></li>
</ul>

The general format for finding bundles is like this:
<pre>http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/[MASTER_HOSTNAME]/jobs/test-portal-acceptance-pullrequest([PORTAL_BRANCH_NAME])/builds/[BUILD_NUMBER]/liferay-portal-bundle-tomcat.zip</pre>

So in this particular case it is located here:
<pre>http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-16/jobs/test-portal-acceptance-pullrequest(master)/builds/1743/liferay-portal-bundle-tomcat.zip</pre>

I'm working on a fix and testing it out here:
https://github.com/ctampoya/liferay-portal/pull/121

Sorry for the inconvenience. :(

**Comment by patriciajeanperez** [comment]
Thanks, @michaelhashimoto!

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by patriciajeanperez** [comment]
ci:retest

**Comment by patriciajeanperez** [comment]
ci:retest

**Pull request closed without merging**
