### PR TITLE
LRQA-69763 | master

### PR DESCRIPTION
**Pull request by susanchen3**
https://issues.liferay.com/browse/LRQA-69763

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
Just started reviewing :)

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
@susanchen3, looks good! reminder to upload an html with a passing test next time. It looks like the one attached in the ticket did not run all the macros. Ran it on my local this time. Thank you!

**Comment by patriciajeanperez** [comment]
ci:reopen

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
