### PR TITLE
LPS-91303

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @patriciajeanperez,

This changes the behaviour of KB when displaying the contents of a
folder. If the folder has both articles and folders, now it will allow
to see those articles by including the root folder in the navigation.

This shouldn't break any existing tests (as it is a new use case), but
I'm sending this to you anyway just in case.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Thanks, @adolfopa!

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/69213

**Pull request closed without merging**
