### PR TITLE
LPS-92325 Moving CSS to the simple view

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/70125

**Pull request closed without merging**
