### PR TITLE
LPS-162569 | master

### PR DESCRIPTION
**Pull request by lilylcl**
https://issues.liferay.com/browse/LPS-162569

### CODE REVIEW

**Comment by lilylcl** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Nice! @lilylcl To make this test run slightly faster, I think we can update this test to open Roles Admin via URL rather than UI. Take a look at Role.openRolesAdmin. Thanks!

**Comment by lilylcl** [comment]
Done and resend.

**Comment by lilylcl** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
