### PR TITLE
LPS-90081 Adding file-card class to get the right icon color

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @patriciajeanperez,

We've changed the stickers for files. We've also moved the lock and shortcut indicators inside the cards. 

Hopefully this won't cause you too much trouble.

Thanks!

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
This is how it looks like now: image

**Comment by patriciajeanperez** [comment]
please see conflicting files @4lejandrito thanks!

**Comment by 4lejandrito** [comment]
See https://github.com/patriciajeanperez/liferay-portal/pull/168.

**Pull request closed without merging**
