### PR TITLE
LRQA-50749, LRQA-50752 | master 

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LRQA-50749
https://issues.liferay.com/browse/LRQA-50752

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Hi @epark18! Tests look good. Please create a ticket with the label `usm-test-refactor` so we can update the tasks to adopt the BDD model. In the same ticket, we can also make it clear as to why it was needed to order the entries by name before asserting pagination.

The SF fixes here were worked on by Melody yesterday (See https://github.com/patriciajeanperez/liferay-portal/pull/521/commits/ace9e7d4935b96f50f74f62d7dc0487166fe1ebb) and is in BChan's queue right now. Once that is merged, can you rebase and resend this pull? Thank you!

**Pull request closed without merging**
