### PR TITLE
LPS-90507 Apply cards to Blogs main view

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @patriciajeanperez 

This should be the complete set of changes for the main view. I'll send you another pull updating the images view (this is already too big of a PR).

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@4lejandrito Here you can see the kind of thing we'll need to do for D&M, so you get an idea of the complexity.

**Comment by patriciajeanperez** [comment]
ci:test:relevant:norebase

**Comment by patriciajeanperez** [comment]
ci:test:relevant:environments

**Comment by patriciajeanperez** [comment]
ci:test:environment

**Pull request closed without merging**
