### PR TITLE
LRQA-54946 | master

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LRQA-54946

Hello Patty,
Since the related commit not merged yet, I'm afraid of causing any conflict if send to BChan directly. Would you please help with sending the commits? Thanks Patty.

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Just started reviewing :)

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/83053

**Pull request closed without merging**
