### PR TITLE
LPS-92323 This class is also specific to DM and has no effect

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @patriciajeanperez,

This might break some of your tests of sharing. I hope it doesn't cause you too much pain.

Feel free to foward it to Brian.

Thanks!

**Comment by patriciajeanperez** [comment]
ci:test:revelant

**Comment by patriciajeanperez** [comment]
ci:test:norebase

**Comment by patriciajeanperez** [comment]
Hey @austinchiang I'm gonna assign this to you. I wasn't able to get good results today due to upstream failures.

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/69830

**Comment by patriciajeanperez** [comment]
Hi @4lejandrito and @austinchiang, I closed the PR to BChan due to integration test failures. Please take a look! Thanks

**Pull request closed without merging**
