### PR TITLE
LPS-91162 Deleting folder too

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hi @patriciajeanperez,

This changes quite a bit the `manage collaborators` dialog. Have a look at [the tickets](https://issues.liferay.com/browse/LPS-91162) for more info.

Thanks!

**Comment by 4lejandrito** [comment]
@ambrinchaudhary, @boton

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/70967

**Pull request closed without merging**
