### PR TITLE
LRQA-69884, LRQA-69885 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-69884
https://issues.liferay.com/browse/LRQA-69885

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Looks good, @melodywu! In a separate ticket, can you update Accounts#CanAddAndRemoveOrganizationsInBulk test to use the new macro `unassignMultipleOrganizations` you created? Thanks!

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
