### PR TITLE
LRQA-70592 | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LRQA-70592

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
No test changes needed :)

**Comment by patriciajeanperez** [comment]
No test changes needed :)

**Comment by patriciajeanperez** [comment]
Pushed to Github.
https://github.com/patriciajeanperez/liferay-portal/pull/442

**Pull request closed without merging**
