### PR TITLE
LPS-86935 Showing error when there is no preview available

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @patriciajeanperez,

Please verify your functional tests.

Thanks a lot!

@boton

**Comment by patriciajeanperez** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Thanks guys @4lejandrito @boton

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/68730

**Pull request closed without merging**
