### PR TITLE
LRQA-38642 | master

### PR DESCRIPTION
**Pull request by timpak**
https://issues.liferay.com/browse/LRQA-38642

### CODE REVIEW

**Comment by timpak** [comment]
@vicnate5 @jpince

**Comment by jpince** [comment]
@timpak thanks!

@patriciajeanperez I recommend https://grow.liferay.com/share/OriginAl to automatically update your origin :)

**Comment by patriciajeanperez** [comment]
No test changes needed :)

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/55458

**Pull request closed without merging**
