### PR TITLE
LRQA-66106 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-66106

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test

**Comment by patriciajeanperez** [comment]
Hi @melodywu, did you mean to send this with the `run pr` commit?

**Comment by melodywu** [comment]
> Hi @melodywu, did you mean to send this with the `run pr` commit?

No, I just can't find a appropriate URL.

**Pull request closed without merging**
