### PR TITLE
LRQA-69719 | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LRQA-69719

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
@epark18, looks good! just need a few minor changes to make the test faster by using JSON where we can and also navigating to portlets via URL. Thank you!

**Comment by epark18** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
No test changes needed :)

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
