### PR TITLE
LPS-90774

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @patriciajeanperez,

This PR contains some markup/CSS cleaning up, so it will probably break some
tests.

Thanks!

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Ran MB tests here: https://github.com/patriciajeanperez/liferay-portal/pull/186

**Comment by patriciajeanperez** [comment]
ci:test:bundle

**Comment by adolfopa** [comment]
Hey @patriciajeanperez 

Any news about this PR? Did it break anything?

Thanks!

**Comment by patriciajeanperez** [comment]
Hi @adolfopa! Apologies, there was a compile issue on Windows last week so I couldn't fix the failing tests. They are all poshi failures so I should be able to push this to pr to BChan today.

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/72019

**Pull request closed without merging**
