### PR TITLE
LPS-162570 | master

### PR DESCRIPTION
**Pull request by lilylcl**
https://issues.liferay.com/browse/LPS-162570

### CODE REVIEW

**Comment by lilylcl** [comment]
ci:test:sf

**Comment by lilylcl** [comment]
Done and resend.

**Comment by lilylcl** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/124550

**Pull request closed without merging**
