### PR TITLE
LPS-91563 Reorder elements in Wiki list display

### PR DESCRIPTION
**Pull request by adolfopa**
@patriciajeanperez Here I've reordered the title and date elements in the Wiki
page and node list display.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/73139

**Pull request closed without merging**
