### PR TITLE
LRQA-78851 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-78851

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Hi @sharryxue, would you be able to look at this PR and review the other tasks under https://issues.liferay.com/browse/LRQA-73479? I want to make sure your requirements when you created this ticket are satisfied. Thank you!

**Comment by Sharryxue** [comment]
Hello @melodywu,
Since the purpose of the refactor is make the add user information steps reusable, would it be better to add a new macro like `addUserInformation` directly instead of rename the macro? This way, we can also minimize the changes impact on other test cases. Thanks in advance.

/cc @patriciajeanperez

**Pull request closed without merging**
