### PR TITLE
LRQA-71408 | master

### PR DESCRIPTION
**Pull request by bronsonsoda**
[https://issues.liferay.com/browse/LRQA-71408](https://issues.liferay.com/browse/LRQA-71408)

### CODE REVIEW

**Comment by bronsonsoda** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Just started reviewing :)

**Review by patriciajeanperez — COMMENTED** [review]
@bronsonsoda Logic looks good! I just had a few comments about SF and making the last task more robust. Let me know if you have any questions. Thanks!

**Comment by bronsonsoda** [comment]
ci:test:sf

**Comment by bronsonsoda** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Looks good, @bronsonsoda! In the future, it would be best practice to run SF before committing your changes. That way, we wouldn't have to have a separate commit for SF changes.

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
