### PR TITLE
LRQA-50757, LRQA-50758 | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LRQA-50757
https://issues.liferay.com/browse/LRQA-50758

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
ci:test:usm

**Comment by epark18** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
