### PR TITLE
LPS-91285

### PR DESCRIPTION
**Pull request by adolfopa**
@patriciajeanperez I've changed a couple of literals ("choose" -> "select") and
some minor CSS styles.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:documents

**Comment by patriciajeanperez** [comment]
See failing tests here: https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=591081135

**Comment by patriciajeanperez** [comment]
Running tests here: https://github.com/patriciajeanperez/liferay-portal/pull/209

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/73501

**Pull request closed without merging**
