### PR TITLE
LRQA-50727 | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LRQA-50727

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Just started reviewing :)

**Comment by patriciajeanperez** [comment]
@epark18, this looks good especially with the assertions of Anonymous Anonymous user. Though, I think this test case was to add coverage for selecting the app and then selecting all entries in that app > anonymize. See [3b](https://docs.google.com/document/d/1jlPC3o-EXHL8bbgrw_5OWm4vumYPFoh1LPFkaNdfuyA/edit#heading=h.2wxpiqo3co1b). Thanks!

**Comment by epark18** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
