### PR TITLE
LRQA-67441 | master 

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LRQA-67441

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
Just started reviewing :)

**Comment by patriciajeanperez** [comment]
Hi @david-gutierrez-mesa, the gotoSelectCategory is causing some flakiness when trying to assert `Treeview#NODE_COLLAPSE_BUTTON`. Would you be able to review this change or removal of the said assertion? It looks like it was only added to make sure the modal is open, but selecting the category frame should have done that already. Thanks!

**Comment by david-gutierrez-mesa** [comment]
Thank you @patriciajeanperez for letting me know. 

LGTM

**Comment by david-gutierrez-mesa** [comment]
ci:forward

**Pull request closed without merging**
