### PR TITLE
LRQA-72650 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-72650

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
@melodywu have you tried using any of the existing locators in RolesPermissionsNavigation?

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
> @melodywu have you tried using any of the existing locators in RolesPermissionsNavigation?

Done

**Comment by patriciajeanperez** [comment]
Hi @melodywu, since you updated the path to use the collapse icon, I think we could just use an existing locator: PERMISSIONS_NAVITEM_SUBITEM_COLLAPSED. That way, it is also consistent with the first nav item which uses PERMISSIONS_NAVITEM_COLLAPSED. Also, please update the test to make sure that the variables are only declared right before the function that will use them. Thanks! Please resend with fix and also make sure to rebase.

**Pull request closed without merging**
