### PR TITLE
LRQA-69891 | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LRQA-69891

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
@epark18 We can also add an account user as Test and assert the admin can remove it, so we can both cover Account User added by the manager and Account User he created.

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
No test changes needed :)

**Comment by patriciajeanperez** [comment]
Pushed to Github.
https://github.com/patriciajeanperez/liferay-portal/pull/442

**Pull request closed without merging**
