### PR TITLE
LPS-168602 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LPS-168602

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
Hi @melodywu, most of these commits were already merged on https://github.com/brianchandotcom/liferay-portal/pull/126354. Please check and resend. Thanks!

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
> Hi @melodywu, most of these commits were already merged on [brianchandotcom#126354](https://github.com/brianchandotcom/liferay-portal/pull/126354). Please check and resend. Thanks!

Done and thanks

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
