### PR TITLE
LRQA-68620 | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LRQA-68620

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
hey @sharryxue, any comments about this change? I saw the conditional was recently added in https://github.com/liferay/liferay-portal/commit/2058380b3a101846eb23c6fc7fb073e644a15311, but it doesn't look like it needed to be part of the test using it. Just wanted to make sure I didn't miss anything before I forward. Thanks!

**Comment by patriciajeanperez** [comment]
Based from discussion with @sharryxue and @epark18:

- Update tests to log in via UI to make sure the assets added via json are added by the new user
- In a separate task or ticket, create new macro to cover the deleted conditional (anonymizing and deleting)

**Comment by epark18** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Nice! Please don't forget to create a ticket for adding a test that covers the removed conditional. @epark18

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
