### PR TITLE
LRQA-72650 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-72650

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Just started reviewing :)

**Comment by patriciajeanperez** [comment]
Please see https://github.com/patriciajeanperez/liferay-portal/pull/547 @melodywu

**Comment by melodywu** [comment]
> Hi @melodywu, LocalFile.Accounts#CanDefineGroupScopePermissionsInRolesAdmin is failing. Please make sure to run all affected tests next time, especially if the change was made in the test case level and not a macro that's being reused. I will go ahead and fix them for now so we can have both tests passing in the next runs.

Ok thanks I will run all testcases next time

**Comment by melodywu** [comment]
> Please see #547 @melodywu

Thank you Patty I don't need to decleared navItem again. I understand now. It is my mistake for RolesPermissionsNavigation#PERMISSIONS_NAVITEM_COLLAPSED.

**Pull request closed without merging**
