### PR TITLE
LPS-90814 Removing oder by col when threads and categories are present

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @patriciajeanperez,

Can you please check this doesn't break any functional tests for message boards?

Thanks!

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hi @patriciajeanperez,

I pushed a new commit.

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/68434

**Pull request closed without merging**
