### PR TITLE
LPS-166386 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LPS-166386

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Review by patriciajeanperez — CHANGES_REQUESTED** [review]
@melodywu See comments. Can we also work with the team that owns Asset Publisher to move these tests to their component? Thanks!

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
> @melodywu See comments. Can we also work with the team that owns Asset Publisher to move these tests to their component? Thanks!

I ask eco and lima team, They say these testcases should not move to their component.

**Comment by patriciajeanperez** [comment]
https://github.com/patriciajeanperez/liferay-portal/pull/677

**Pull request closed without merging**
