### PR TITLE
LPS-89922

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @patriciajeanperez,

Here we add the "View More" button to the [+] action button in
documents and media.  The idea is to accomodate all available document
types without cluttering the UI too much.

If you need to see the feature in action, you'll need to have at least
10 document types. At that point, a new "view more" button will be
available.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/70124

**Pull request closed without merging**
