### PR TITLE
LRQA-50736 | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LRQA-50736

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Hi @epark18, great job with sorting the data! To make this test more complete, I think we should also make assertions that the Order By and sort actually worked. I think we can do it by changing the pagination to the lowest, to be able to assert an entry is present and not present. A similar test to look into would be `UsersAdmin#BulkDeactivateUserSucceed`

**Comment by epark18** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
