### PR TITLE
LRQA-50468 | add retry

### PR DESCRIPTION
**Pull request by patriciajeanperez**

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:test

**Comment by patriciajeanperez** [comment]
ci:test

**Comment by patriciajeanperez** [comment]
ci:test

**Comment by patriciajeanperez** [comment]
ci:test

**Comment by patriciajeanperez** [comment]
ci:test

**Comment by Sharryxue** [comment]
Hello @patriciajeanperez ,
After checking the [latest results](https://testray.liferay.com/zh/home/-/testray/case_results?testrayBuildId=678155604) as well as all previous results, the failed case not fails for the same reason any more, I'll go ahead pushing the TF you made to BChan to make the case more stable.

**Comment by Sharryxue** [comment]
Pushed to BChan.
[brianchandotcom/liferay-portal#75799](https://github.com/brianchandotcom/liferay-portal/pull/75799)

**Pull request closed without merging**
