### PR TITLE
LRQA-73679 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-73679

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Thanks @melodywu! Looks so much better and the test case is doing what we want to achieve. I just have a couple of changes in terms of naming and grouping according to tasks. Please see https://github.com/patriciajeanperez/liferay-portal/pull/600 and let me know if you have any comments or questions!

**Comment by patriciajeanperez** [comment]
Note that all the prerequisites are added in the Given statement. So I moved assigning users from When to Given. @melodywu

**Pull request closed without merging**
