### PR TITLE
LRQA-63577 | master

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LRQA-63577

Hello @patriciajeanperez,
The failed POSHI test seems due to [LPS-123107](https://issues.liferay.com/browse/LPS-123107), I assuming the changes in [LPS-123107](https://issues.liferay.com/browse/LPS-123107) were supposed not displays the country and region after upgrade and made test-fix based on that, the test would failed for [LPS-124495](https://issues.liferay.com/browse/LPS-124495) after the test-fix. Correct me if I were wrong, thanks in advance.

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
ci:test:stable

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
