### PR TITLE
LPS-93895 give value to serviceContext for the test

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
Hi @patriciajeanperez 

This is a flaky test that we can't reproduce naturally on our machines.
We made some changes on the generation of the Dates (test fail for them) and I think that now the test is running ok.
Can you do me the favor to test several times it to see if I'm correct?

Thanks for all.

**Comment by patriciajeanperez** [comment]
Thanks, @AliciaGarciaGarcia! I'll keep an eye on it!

**Comment by patriciajeanperez** [comment]
ci:test:messageboards

**Comment by patriciajeanperez** [comment]
ci:test:messageboards

**Comment by patriciajeanperez** [comment]
ci:test:messageboards

**Comment by patriciajeanperez** [comment]
Hi @AliciaGarciaGarcia, is this ok to push to BChan after running some tests? Thanks!

**Comment by patriciajeanperez** [comment]
ci:test:messageboards

**Comment by patriciajeanperez** [comment]
ci:test:messageboards

**Comment by patriciajeanperez** [comment]
ci:test:messageboards

**Comment by AliciaGarciaGarcia** [comment]
Hi @patriciajeanperez 
If the test if not failing I think it is ok to merge it.

Thanks for all!

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/73968

**Pull request closed without merging**
