### PR TITLE
LRQA-72783 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-72783

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
@melodywu Closing PR since not all tests were fixed. Please resend, thanks!

**Comment by melodywu** [comment]
> @melodywu Closing PR since not all tests were fixed. Please resend, thanks!

Done

**Comment by melodywu** [comment]
> @melodywu Closing PR since not all tests were fixed. Please resend, thanks!

Done sorry for the mistake.

**Pull request closed without merging**
