### PR TITLE
LPS-115200 Back button not working after editing an Organization

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:relevant

**Comment by patriciajeanperez** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Ran tests here: https://github.com/patriciajeanperez/liferay-portal/pull/293. Will be sending another pull to fwd

**Pull request closed without merging**
