### PR TITLE
LRQA-79808 Move components to PEDS

### PR DESCRIPTION
**Pull request by patriciajeanperez**
https://issues.liferay.com/browse/LRQA-79808

### CODE REVIEW

**Comment by manoelcyreno** [comment]
LGTM

**Comment by manoelcyreno** [comment]
ci:test:frontend

**Comment by manoelcyreno** [comment]
ci:test:frontend

**Comment by manoelcyreno** [comment]
@patriciajeanperez , do you have some idea about why this error appears and we can not call the FI Test suite?

**Comment by manoelcyreno** [comment]
ci:test:frontend

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
