### PR TITLE
LPS-91559 Add icons to D&M plus menu

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @patriciajeanperez ,

I've changed the order of the actions (File Upload and Multiple Upload are one after the other now) and added some icons (so the markup has changed a little bit).

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/70960

**Pull request closed without merging**
