### PR TITLE
LPS-90659 / LPS-90657 Clean up folder actions

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @patriciajeanperez,

Here I've changed the name of the "Subfolder" action to "Folder" in
the [+] menu, and removed the "Add Subfolder" from the set of folder
actions.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Just started reviewing :)

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/70320

**Pull request closed without merging**
