### PR TITLE
LPS-94166 Changing testcases

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @patriciajeanperez,

We are changing the wwe ay storage sizes are formatted. Now instead of `5MB` it will be `5 MB`. We have fixed the unit tests and changed many testcases too.

Hopefully we won't cause you too much trouble.

Thanks!

@AliciaGarciaGarcia

**Comment by austinchiang** [comment]
ci:test

**Comment by austinchiang** [comment]
ci:test:bundle

**Comment by austinchiang** [comment]
Hey @4lejandrito @patriciajeanperez , @hanlf will review this pull and push to BChan if it's good. Thanks!

**Comment by Hanlf** [comment]
ci:retest

**Comment by Hanlf** [comment]
The above failures are not related to this pull.
Update one testcase about 0 B.

Pushed to BChan: https://github.com/brianchandotcom/liferay-portal/pull/71846

cc/ @austinchiang @4lejandrito

**Pull request closed without merging**
