### PR TITLE
LPS-90812

### PR DESCRIPTION
**Pull request by adolfopa**
@patriciajeanperez Some changes to the markup and CSS styles.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:messageboards

**Comment by patriciajeanperez** [comment]
See failing tests here: https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=591078212

**Comment by patriciajeanperez** [comment]
Just started reviewing :)

**Comment by patriciajeanperez** [comment]
Pushed test fixes to https://github.com/adolfopa/liferay-portal/pull/979, please check the SF errors on language keys @adolfopa. Thank you!

**Pull request closed without merging**
