### PR TITLE
LRQA-76053 | master

### PR DESCRIPTION
**Pull request by lilylcl**
https://issues.liferay.com/browse/LRQA-76053

### CODE REVIEW

**Comment by lilylcl** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
Hello @lilylcl,
There is another test _ViewPortalConfigurationAfterUpgrade*_ in the file and not add case for 740/7413 yet, will you working on another ticket? Or there are commits missing here, would you please help with confirm? Thanks in advance.

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
