### PR TITLE
LPS-115200 Back button not working after editing an Organization

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Just started reviewing :)

**Comment by patriciajeanperez** [comment]
Thank you, @pei-jung! Looks like the failures are test fixes. I will send a new pull with the fix.

**Pull request closed without merging**
