### PR TITLE
LPS-83172 Auto SF

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hi @patriciajeanperez,

We've changed the creation menu in DM a little bit. This might break some functional tests.

We've also removed the default document types (marketing banner, sales presentation, etc...) and I think you guys were using them in some tests. You might want to update / delete them.

Feel free to forward to Brian when you're done.

Thanks a lot!

**Comment by patriciajeanperez** [comment]
ci:test:bundle

**Comment by patriciajeanperez** [comment]
Just started reviewing :)

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/68799

**Pull request closed without merging**
