### PR TITLE
LRQA-69848 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-69848

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:account

**Comment by melodywu** [comment]
ci:test:comment

**Comment by melodywu** [comment]
ci:test:workflow

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
No related issue found in ci:test:account and ci:test:workflow

**Comment by patriciajeanperez** [comment]
Hi @melodywu, there are no commits that removed Accounts.testcase and Accounts.macro so we have both Accounts and Account test cases and macros. Can you please check and rebase? Thank you! 

cc @sharryxue

**Comment by melodywu** [comment]
Hi Patty，How to deal with the conflicts， thanks a lot.

**Comment by melodywu** [comment]
https://github.com/patriciajeanperez/liferay-portal/pull/707

**Pull request closed without merging**
