### PR TITLE
LRQA-57521 | master

### PR DESCRIPTION
**Pull request by patriciajeanperez**

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
ci:test:revelant

**Comment by patriciajeanperez** [comment]
ci:test:accounts

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
The failed case is due to the status value changed, addressed the issue in [LRQA-59012](https://issues.liferay.com/browse/LRQA-59012).

**Pull request closed without merging**
