### PR TITLE
LRQA-33600 | master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-33600

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:reopen

**Comment by austinchiang** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by patriciajeanperez** [comment]
No test changes needed :)

**Comment by patriciajeanperez** [comment]
Pushed to BChan:
brianchandotcom#50156

**Pull request closed without merging**
