### PR TITLE
LPS-93448 Don't use "subcategory" to refer to child categories

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @patriciajeanperez,

Here I've changed another occurrence of "subcategory" in MB.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/70963

**Pull request closed without merging**
