### PR TITLE
LRQA-66200 | master

### PR DESCRIPTION
**Pull request by patriciajeanperez**
https://issues.liferay.com/browse/LRQA-66200

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:accounts

**Comment by Sharryxue** [comment]
Resend the pr by adding additional changes.
[Sharryxue/liferay-portal#257](https://github.com/Sharryxue/liferay-portal/pull/257)

**Pull request closed without merging**
