### PR TITLE
LPS-95721

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @patriciajeanperez,

In addition to the changes described in the ticket, now visible items don't have
an explicit status (the tag "visible" is not displayed).  We expect the majority
of assets to be visible, so this removes a lot of line noise.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:sharing

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/73867
https://github.com/brianchandotcom/liferay-portal-ee/pull/24758

**Pull request closed without merging**
