### PR TITLE
LRQA-71317 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-71317

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
@melodywu hmm I don't think we want to assert the elements in those page from the screenshot because those are not the ones we expect to see after saving the permissions. Can we assert something else to make sure that the page is already back in the `Define Group Scope Permissions`. We might also need to add pause as a workaround just to see if the test is just loading slowly.

In addition, please add temporary settings to be able to run the test on CI when I review. Thanks!

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
