### PR TITLE
LPS-90081 Adding file-card class to get the right icon color

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Tests ran in https://github.com/patriciajeanperez/liferay-portal/pull/164

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/70301

**Comment by 4lejandrito** [comment]
Thanks Patricia!

**Pull request closed without merging**
