### PR TITLE
LPS-90757 Only owner and admins can do the initial share

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @patriciajeanperez,

Due to some limitations, we need to change the way sharing works. The
new behaviour is:

1. If the user is the owner of a document, or a group/company admin,
he/she can share the document.

2. Otherwise, only if the document has been shared with him as
"shareable" he'll be able to share it.

Previously, any user was able to share any document as long as he had
VIEW permissions. This made it impossible to forbid resharing in some
cases.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:bundle

**Comment by patriciajeanperez** [comment]
Just started reviewing :)

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/68417

**Pull request closed without merging**
