### PR TITLE
LPS-90739 Remove usage of "subcategory"

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @patriciajeanperez,

Here I've removed the usage of "Subcategory" in the plus action button of
message boards.  We'll use "category" for both categories and subcategories.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Running MB tests that adds subcategories: https://github.com/patriciajeanperez/liferay-portal/pull/175

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/70766

**Pull request closed without merging**
