### PR TITLE
LRQA-71317 | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LRQA-71317

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:test:account

**Comment by epark18** [comment]
ci:test:account

**Comment by epark18** [comment]
ci:test:account

**Comment by epark18** [comment]
ci:test:account

**Comment by patriciajeanperez** [comment]
yay! @epark18

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
