### PR TITLE
LRQA-71834 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-71834
I ran them here [melodywu#27](https://github.com/melodywu/liferay-portal/pull/27).

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
ci:test:account

**Comment by patriciajeanperez** [comment]
- Please review the failures from ci:test:account @melodywu 
- Since adding a user will be done via JSON, there is no need to navigate to the Users section in the UI before adding or assigning the user via JSON. Please update all tests to make sure they don't have unnecessary steps before the creation or assigning of user.

**Comment by melodywu** [comment]
> * Please review the failures from ci:test:account @melodywu
> * Since adding a user will be done via JSON, there is no need to navigate to the Users section in the UI before adding or assigning the user via JSON. Please update all tests to make sure they don't have unnecessary steps before the creation or assigning of user.

ok

**Pull request closed without merging**
